from app.api import bp
from flask import Blueprint, request, jsonify

@bp.route('/events', methods=['GET'])
def getPetEvent():
    null = None
    res ={}
    res["status_code"] =200
    res["data"] =[
    {
      "id": 15875,
      "title": "Vacxin mũi 4 bệnh lần3",
      "facility": null,
      "address": null,
      "date": "16\/11\/2021",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1654,
      "boss_name": "check 611",
      "boss_avatar": "storage\/pets\/avatar_698855966_c0-bd90-4b7d.png",
      "boss_gender": "lgbt",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 13204,
      "title": "Tẩy giun lần4",
      "facility": null,
      "address": null,
      "date": "17\/11\/2021",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1587,
      "boss_name": "ppppiiio",
      "boss_avatar": "storage\/pets\/avatar_629931754_27-3b2a-4405.png",
      "boss_gender": "male",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15667,
      "title": "Tẩy giun lần1",
      "facility": null,
      "address": null,
      "date": "18\/11\/2021",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1641,
      "boss_name": "oke",
      "boss_avatar": "storage\/pets\/avatar_630946400_c2-cdea-4a7c.png",
      "boss_gender": "female",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15631,
      "title": "Tẩy giun lần2",
      "facility": null,
      "address": null,
      "date": "22\/11\/2021",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1631,
      "boss_name": "chó cn",
      "boss_avatar": "storage\/pets\/avatar_630925562_53-f7de-4d5a.png",
      "boss_gender": "male",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15634,
      "title": "Tẩy giun lần2",
      "facility": null,
      "address": null,
      "date": "22\/11\/2021",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1632,
      "boss_name": "aaaaaaa edit",
      "boss_avatar": "storage\/pets\/avatar_630937850_be-aa6d-41fe.png",
      "boss_gender": "lgbt",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15795,
      "title": "Tẩy giun lần2",
      "facility": null,
      "address": null,
      "date": "22\/11\/2021",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1646,
      "boss_name": "pet 3\/11",
      "boss_avatar": "storage\/pets\/avatar_672994005_9b-8e8b-4f80.png",
      "boss_gender": "female",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15583,
      "title": "Tẩy giun lần2",
      "facility": null,
      "address": null,
      "date": "22\/11\/2021",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1630,
      "boss_name": "final",
      "boss_avatar": "storage\/pets\/avatar_667898394_68-05b5-4aec.png",
      "boss_gender": "female",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15662,
      "title": "Tẩy giun lần2",
      "facility": null,
      "address": null,
      "date": "24\/11\/2021",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1640,
      "boss_name": "pet thêm",
      "boss_avatar": "storage\/pets\/avatar_630896908_75-ce2f-4f5c.png",
      "boss_gender": "male",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15878,
      "title": "Tẩy giun lần4",
      "facility": null,
      "address": null,
      "date": "26\/11\/2021",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1654,
      "boss_name": "check 611",
      "boss_avatar": "storage\/pets\/avatar_698855966_c0-bd90-4b7d.png",
      "boss_gender": "lgbt",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15695,
      "title": "Tẩy giun lần2",
      "facility": null,
      "address": null,
      "date": "01\/12\/2021",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1611,
      "boss_name": "pet của taooooo",
      "boss_avatar": "storage\/pets\/avatar_629808188_31-6227-45e0.png",
      "boss_gender": "lgbt",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15697,
      "title": "Tẩy giun lần2",
      "facility": null,
      "address": null,
      "date": "01\/12\/2021",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1618,
      "boss_name": "ycchc",
      "boss_avatar": "storage\/pets\/avatar_630995561_39-6a47-4b53.png",
      "boss_gender": "lgbt",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15580,
      "title": "Vacxin mũi 4 bệnh lần1",
      "facility": null,
      "address": null,
      "date": "01\/12\/2021",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1630,
      "boss_name": "final",
      "boss_avatar": "storage\/pets\/avatar_667898394_68-05b5-4aec.png",
      "boss_gender": "female",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15659,
      "title": "Vacxin mũi 4 bệnh lần1",
      "facility": null,
      "address": null,
      "date": "03\/12\/2021",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1640,
      "boss_name": "pet thêm",
      "boss_avatar": "storage\/pets\/avatar_630896908_75-ce2f-4f5c.png",
      "boss_gender": "male",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15876,
      "title": "Vacxin FIP lần1",
      "facility": null,
      "address": null,
      "date": "05\/12\/2021",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1654,
      "boss_name": "check 611",
      "boss_avatar": "storage\/pets\/avatar_698855966_c0-bd90-4b7d.png",
      "boss_gender": "lgbt",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15877,
      "title": "Vacxin phòng dại lần1",
      "facility": null,
      "address": null,
      "date": "05\/12\/2021",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1654,
      "boss_name": "check 611",
      "boss_avatar": "storage\/pets\/avatar_698855966_c0-bd90-4b7d.png",
      "boss_gender": "lgbt",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15888,
      "title": "Tẩy giun lần2",
      "facility": null,
      "address": null,
      "date": "08\/12\/2021",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1619,
      "boss_name": "test",
      "boss_avatar": "storage\/pets\/avatar_667987084_d5-5353-47e2.png",
      "boss_gender": "male",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15364,
      "title": "Vacxin mũi 4 bệnh lần1",
      "facility": null,
      "address": null,
      "date": "10\/12\/2021",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1611,
      "boss_name": "pet của taooooo",
      "boss_avatar": "storage\/pets\/avatar_629808188_31-6227-45e0.png",
      "boss_gender": "lgbt",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15960,
      "title": "Tẩy giun lần2",
      "facility": null,
      "address": null,
      "date": "10\/12\/2021",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1625,
      "boss_name": "mai check 1 edit",
      "boss_avatar": "storage\/pets\/avatar_630995340_8a-960f-4dba.png",
      "boss_gender": "male",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15630,
      "title": "Vacxin phòng dại lần1",
      "facility": null,
      "address": null,
      "date": "01\/01\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1631,
      "boss_name": "chó cn",
      "boss_avatar": "storage\/pets\/avatar_630925562_53-f7de-4d5a.png",
      "boss_gender": "male",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15633,
      "title": "Vacxin phòng dại lần1",
      "facility": null,
      "address": null,
      "date": "01\/01\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1632,
      "boss_name": "aaaaaaa edit",
      "boss_avatar": "storage\/pets\/avatar_630937850_be-aa6d-41fe.png",
      "boss_gender": "lgbt",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15794,
      "title": "Vacxin phòng dại lần1",
      "facility": null,
      "address": null,
      "date": "01\/01\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1646,
      "boss_name": "pet 3\/11",
      "boss_avatar": "storage\/pets\/avatar_672994005_9b-8e8b-4f80.png",
      "boss_gender": "female",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15482,
      "title": "Vacxin phòng dại lần1",
      "facility": null,
      "address": null,
      "date": "10\/01\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1618,
      "boss_name": "ycchc",
      "boss_avatar": "storage\/pets\/avatar_630995561_39-6a47-4b53.png",
      "boss_gender": "lgbt",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15499,
      "title": "Vacxin phòng dại lần1",
      "facility": null,
      "address": null,
      "date": "18\/01\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1619,
      "boss_name": "test",
      "boss_avatar": "storage\/pets\/avatar_667987084_d5-5353-47e2.png",
      "boss_gender": "male",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15582,
      "title": "Vacxin phòng dại lần1",
      "facility": null,
      "address": null,
      "date": "01\/02\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1630,
      "boss_name": "final",
      "boss_avatar": "storage\/pets\/avatar_667898394_68-05b5-4aec.png",
      "boss_gender": "female",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15660,
      "title": "Vacxin FIP lần1",
      "facility": null,
      "address": null,
      "date": "03\/02\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1640,
      "boss_name": "pet thêm",
      "boss_avatar": "storage\/pets\/avatar_630896908_75-ce2f-4f5c.png",
      "boss_gender": "male",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15661,
      "title": "Vacxin phòng dại lần1",
      "facility": null,
      "address": null,
      "date": "03\/02\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1640,
      "boss_name": "pet thêm",
      "boss_avatar": "storage\/pets\/avatar_630896908_75-ce2f-4f5c.png",
      "boss_gender": "male",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15365,
      "title": "Vacxin FIP lần1",
      "facility": null,
      "address": null,
      "date": "10\/02\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1611,
      "boss_name": "pet của taooooo",
      "boss_avatar": "storage\/pets\/avatar_629808188_31-6227-45e0.png",
      "boss_gender": "lgbt",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15366,
      "title": "Vacxin phòng dại lần1",
      "facility": null,
      "address": null,
      "date": "10\/02\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1611,
      "boss_name": "pet của taooooo",
      "boss_avatar": "storage\/pets\/avatar_629808188_31-6227-45e0.png",
      "boss_gender": "lgbt",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 13202,
      "title": "Vacxin mũi 5 hoặc 7 bệnh lần4",
      "facility": null,
      "address": null,
      "date": "02\/04\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1587,
      "boss_name": "ppppiiio",
      "boss_avatar": "storage\/pets\/avatar_629931754_27-3b2a-4405.png",
      "boss_gender": "male",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 13203,
      "title": "Vacxin phòng dại lần2",
      "facility": null,
      "address": null,
      "date": "02\/04\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1587,
      "boss_name": "ppppiiio",
      "boss_avatar": "storage\/pets\/avatar_629931754_27-3b2a-4405.png",
      "boss_gender": "male",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15796,
      "title": "Vacxin mũi 5 hoặc 7 bệnh lần4",
      "facility": null,
      "address": null,
      "date": "01\/05\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1647,
      "boss_name": "pet 3\/11 l2",
      "boss_avatar": "storage\/pets\/avatar_672994391_fa-8f0e-4613.png",
      "boss_gender": "female",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15797,
      "title": "Vacxin phòng dại lần2",
      "facility": null,
      "address": null,
      "date": "01\/05\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1647,
      "boss_name": "pet 3\/11 l2",
      "boss_avatar": "storage\/pets\/avatar_672994391_fa-8f0e-4613.png",
      "boss_gender": "female",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 16088,
      "title": "Vacxin mũi 4 bệnh lần4",
      "facility": null,
      "address": null,
      "date": "05\/08\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1654,
      "boss_name": "check 611",
      "boss_avatar": "storage\/pets\/avatar_698855966_c0-bd90-4b7d.png",
      "boss_gender": "lgbt",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15986,
      "title": "Vacxin mũi 5 hoặc 7 bệnh lần4",
      "facility": null,
      "address": null,
      "date": "01\/10\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1631,
      "boss_name": "chó cn",
      "boss_avatar": "storage\/pets\/avatar_630925562_53-f7de-4d5a.png",
      "boss_gender": "male",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15988,
      "title": "Vacxin mũi 5 hoặc 7 bệnh lần4",
      "facility": null,
      "address": null,
      "date": "01\/10\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1646,
      "boss_name": "pet 3\/11",
      "boss_avatar": "storage\/pets\/avatar_672994005_9b-8e8b-4f80.png",
      "boss_gender": "female",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15987,
      "title": "Vacxin mũi 5 hoặc 7 bệnh lần4",
      "facility": null,
      "address": null,
      "date": "26\/10\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1632,
      "boss_name": "aaaaaaa edit",
      "boss_avatar": "storage\/pets\/avatar_630937850_be-aa6d-41fe.png",
      "boss_gender": "lgbt",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15994,
      "title": "Vacxin mũi 4 bệnh lần6",
      "facility": null,
      "address": null,
      "date": "13\/11\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1661,
      "boss_name": "bach_test_8_11",
      "boss_avatar": "storage\/pets\/avatar_672812975_e0-a66f-42fb.png",
      "boss_gender": "male",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15995,
      "title": "Vacxin FIP lần5",
      "facility": null,
      "address": null,
      "date": "13\/11\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1661,
      "boss_name": "bach_test_8_11",
      "boss_avatar": "storage\/pets\/avatar_672812975_e0-a66f-42fb.png",
      "boss_gender": "male",
      "note": null,
      "type": 4,
      "age": ""
    },
    {
      "id": 15996,
      "title": "Vacxin phòng dại lần4",
      "facility": null,
      "address": null,
      "date": "13\/11\/2022",
      "hour": "10:00",
      "status": 1,
      "boss_id": 1661,
      "boss_name": "bach_test_8_11",
      "boss_avatar": "storage\/pets\/avatar_672812975_e0-a66f-42fb.png",
      "boss_gender": "male",
      "note": null,
      "type": 4,
      "age": ""
    }
  ]
    return jsonify(res)